name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: show_mem_free
      run: free -m
    - name: show_disk_free
      run: df -h
    - name: test
      run: ./test_sqlite_blaster -t
