orbs:
  aws-cli: circleci/aws-cli@1.0.0 #See: https://circleci.com/orbs/registry/orb/circleci/aws-cli

version: 2.1
jobs:
  # TODO: tests
  # test:
  #   docker:
  #     - image: cimg/go:1.18
  #   steps:
  #     - checkout
  #     - run:
  #         name: Test ethdb/cdc
  #         command: go test ./ethdb/cdc
  #     - run:
  #         name: Test replica
  #         command: go test ./replica
  build_push:
    docker: # run the steps with Docker
      - image: cimg/go:1.18.6 # ...with this image as the primary container
      # this is where all `steps` will run
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prep env
          command: |
            sudo apt update
            sudo apt install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
            mkdir -p /home/circleci/go/src
            go get
      - run:
          name: build image
          command: |
            export GOPATH=$HOME/go
            export GOARCH=amd64
            go build -o flume-amd64
            CC=aarch64-linux-gnu-gcc  CGO_ENABLED=1 GOARCH=arm64 go build -o flume-arm64
            go build -buildmode=plugin -o ./polygon-amd64.so plugins/packages/polygon/*.go
            CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 GOARCH=arm64 go build -buildmode=plugin -o ./polygon-arm64.so plugins/packages/polygon/*.go
      # - run:
      #     name: build image
      #     command: |
      #       export GOPATH=$HOME/go
      #       make geth-linux-amd64
      - aws-cli/setup: #See: https://circleci.com/orbs/registry/orb/circleci/aws-cli
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: push to s3
          command: |
            aws s3 cp ./flume-amd64 s3://ethercattle-binaries/flume/$CIRCLE_TAG/flume-amd64 --acl=public-read
            aws s3 cp ./flume-arm64 s3://ethercattle-binaries/flume/$CIRCLE_TAG/flume-arm64 --acl=public-read
            aws s3 cp ./polygon-amd64.so s3://ethercattle-binaries/flume/$CIRCLE_TAG/polygon-amd64.so --acl=public-read
            aws s3 cp ./polygon-arm64.so s3://ethercattle-binaries/flume/$CIRCLE_TAG/polygon-arm64.so --acl=public-read
      - run:
          name: Message Slack
          command: |
              ./.circleci/slack-post.sh -w $SlackWebhook -m "*flume*:\nTag: $CIRCLE_TAG"


workflows:
  version: 2
  build_and_test:
    jobs:
      # - test:
      #     filters:  # required since `deploy` has tag filters AND requires `build`
      #       tags:
      #         only: /.*/
      - build_push:
          # requires:
          #   - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
