networkName: mainnet
brokers:
 - url: null://
loggingLevel: debug
databases:
  blocks: ../testing-resources/blocks.sqlite
  transactions: ../testing-resources/transactions.sqlite
  logs: ../testing-resources/logs.sqlite
  mempool: ../testing-resources/mempool.sqlite
heavyserver:
  "mock"
